"""add access token table

Revision ID: 1251637d6441
Revises: c43b30675302
Create Date: 2024-11-09 17:31:40.597350

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1251637d6441"
down_revision: Union[str, None] = "c43b30675302"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("id", sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f("uq_users_id"), "users", ["id"])
    op.drop_column("users", "userId")
    op.create_table(
        "accesstokens",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_accesstokens_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_accesstokens")),
    )
    op.create_index(
        op.f("ix_accesstokens_created_at"),
        "accesstokens",
        ["created_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("userId", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_users_id"), "users", type_="unique")
    op.drop_column("users", "id")
    op.drop_index(op.f("ix_accesstokens_created_at"), table_name="accesstokens")
    op.drop_table("accesstokens")
    # ### end Alembic commands ###
