"""fastapi-users user table

Revision ID: c43b30675302
Revises: bce5c7b3d176
Create Date: 2024-11-09 14:41:10.723374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c43b30675302"
down_revision: Union[str, None] = "bce5c7b3d176"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("userId", sa.Integer(), nullable=False))
    op.add_column(
        "users", sa.Column("userName", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("profilePic", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("phoneNumber", sa.String(length=10), nullable=True)
    )
    op.add_column("users", sa.Column("rating", sa.Float(), nullable=True))
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
    )
    op.add_column(
        "users", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("is_superuser", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("is_verified", sa.Boolean(), nullable=False)
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=320),
        existing_nullable=False,
    )
    op.drop_column("users", "password")
    op.drop_column("users", "user_name")
    op.drop_column("users", "status")
    op.drop_column("users", "verified_at")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "user_id")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "verified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "status",
            sa.VARCHAR(),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "user_name",
            sa.VARCHAR(length=150),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "password",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=320),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("users", "is_verified")
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "rating")
    op.drop_column("users", "phoneNumber")
    op.drop_column("users", "profilePic")
    op.drop_column("users", "userName")
    op.drop_column("users", "userId")
    # ### end Alembic commands ###
