http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
  baseUrl: "http://localhost:8000"
postgres:
  username: "postgres"
  host: "db"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"
fileStorage:
  url: website.yandexcloud.net
  bucket: profile-pictures
smtp:
  host: "smtp.mail.ru"
  port: 465
  from: "renting-app@mail.ru"
auth:
  accessTokenTTL: 3h
  refreshTokenTTL: 720h
  verificationCodeLength: 8
email:
  templates:
    verification_email: "./templates/verification_code.html"
    reset_email: "./templates/reset_password.html"
