http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
postgres:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"
fileStorage:
  url: ams3.digitaloceanspaces.com
  bucket: courses
auth:
  accessTokenTTL: 5m
  refreshTokenTTL: 720h 
  verificationCodeLength: 8