postgres:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
redis:
  host: "localhost"
  port: "6379"
auth:
  accessTokenTTL: 24h
  refreshTokenTTL: 720h
  verificationCodeLength: 8
