http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
  baseUrl: "http://localhost:8000"
fileStorage:
  url: website.yandexcloud.net
  bucket: profile-pictures
smtp:
  host: "smtp.mail.ru"
  port: 465
  from: "renting-app@mail.ru"
email:
  templates:
    verification_email: "./templates/verification_code.html"
    reset_email: "./templates/reset_password.html"
