postgres:
  username: "postgres"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
redis:
  host: "redis"
  port: "6379"
  cacheTTL: 1m
auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 720h
  verificationCodeLength: 8
